### ISSUE TITLE
SIGSEGV on GitHub Actions with v1.55.0

### ISSUE THREAD

**Issue by selfagency** [k1LoW/tbls#344]
### What happened

Everything was working great until this morning when the latest version update was pushed.

```sh
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f3c6c8695ca]
```

```yaml
      - name: Validate database schema
        env:
          DEBUG: 1
        run: |
          source <(curl -sL https://git.io/use-tbls)
          tbls version
          yarn workspace backend db:docs:diff
          yarn workspace backend db:lint
```

```json
    "db:docs:diff": "tbls diff",
    "db:lint": "tbls lint",
```

### What stack trace or error message from tbls did you see?

```
$ tbls diff
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7ff9c97445ca]

runtime stack:
runtime.throw({0x1a3e332, 0x7ff9ac000d53})
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 6 [syscall]:
runtime.cgocall(0x144ab30, 0xc00006b590)
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc00006b568 sp=0xc00006b530 pc=0x40597c
net._C2func_getaddrinfo(0xc0000bc290, 0x0, 0xc0004fe210, 0xc00012c030)
	_cgo_gotypes.go:91 +0x56 fp=0xc00006b590 sp=0xc00006b568 pc=0x5c8176
net.cgoLookupIPCNAME.func1({0xc0000bc290, 0x0, 0x0}, 0xc0000bc[27](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5821704171?check_suite_focus=true#step:9:27)0, 0xc00006b650)
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc00006b5e8 sp=0xc00006b590 pc=0x5c9ebf
net.cgoLookupIPCNAME({0x19fbd75, 0x3}, {0xc0000bc270, 0x0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc00006b738 sp=0xc00006b5e8 pc=0x5c970d
net.cgoIPLookup(0x2b777d0, {0x19fbd75, 0xc0000bc[28](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5821704171?check_suite_focus=true#step:9:28)0}, {0xc0000bc270, 0x0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc00006b7a8 sp=0xc00006b738 pc=0x5c9f7b
net.cgoLookupIP·dwrap·25()
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc00006b7e0 sp=0xc00006b7a8 pc=0x5ca3f6
runtime.goexit()
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00006b7e8 sp=0xc00006b7e0 pc=0x4661e1
created by net.cgoLookupIP
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:230 +0x125

goroutine 1 [select]:
net.(*Resolver).lookupIPAddr(0x2b777c0, {0x1e5ab88, 0xc00011e000}, {0x19fbd75, 0xc0007be958}, {0xc0000bc270, 0x9})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0x1e5ab88, {0x1e5ab88, 0xc00011e000}, {0x19fbd75, 0x3}, {0xc0000bc270, 0xe})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0xc00011e000, {0x1e5ab88, 0xc00011e000}, {0x19fc737, 0x4}, {0x19fbd75, 0xc0007beb78}, {0xc0000bc270, 0xe}, {0x0, ...})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0xc0007becb0, {0x1e5ab88, 0xc00011e000}, {0x19fbd75, 0x1a0[29](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5821704171?check_suite_focus=true#step:9:29)99}, {0xc0000bc270, 0x4})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/dial.go:406 +0x448
github.com/lib/pq.defaultDialer.DialContext(...)
	/home/runner/go/pkg/mod/github.com/lib/pq@v1.10.4/conn.go:119
github.com/lib/pq.dial({0x1e5ab88, 0xc00011e000}, {0x1e46790, 0xc00007e240}, 0x1e46790)
	/home/runner/go/pkg/mod/github.com/lib/pq@v1.10.4/conn.go:417 +0x3e9
github.com/lib/pq.(*Connector).open(0xc000128888, {0x1e5ab88, 0xc00011e000})
	/home/runner/go/pkg/mod/github.com/lib/pq@v1.10.4/conn.go:354 +0x225
github.com/lib/pq.DialOpen({0x1e46790, 0xc00007e240}, {0xc000049500, 0x18})
	/home/runner/go/pkg/mod/github.com/lib/pq@v1.10.4/conn.go:326 +0x7a
github.com/lib/pq.Open(...)
	/home/runner/go/pkg/mod/github.com/lib/pq@v1.10.4/conn.go:316
github.com/lib/pq.Driver.Open({}, {0xc000049500, 0x56})
	/home/runner/go/pkg/mod/github.com/lib/pq@v1.10.4/conn.go:54 +0x7a
database/sql.dsnConnector.Connect(...)
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:761
database/sql.(*DB).conn(0xc000857380, {0x1e5ab88, 0xc00011e000}, 0x1)
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:1364 +0x7ac
database/sql.(*DB).query(0xc0000c61c0, {0x1e5ab88, 0xc00011e000}, {0x1a639dc, 0x3a8}, {0xc0007bf8a8, 0x1, 0x1}, 0xf0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:1695 +0x5d
database/sql.(*DB).QueryContext(0x427d, {0x1e5ab88, 0xc00011e000}, {0x1a639dc, 0x3a8}, {0xc0007bf8a8, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:1674 +0xdf
database/sql.(*DB).Query(...)
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:1691
github.com/k1LoW/tbls/drivers/postgres.(*Postgres).Analyze(0xc0000c6000, 0xc0007f1c00)
	/home/runner/work/tbls/tbls/drivers/postgres/postgres.go:141 +0xe72
github.com/k1LoW/tbls/datasource.Analyze({{0xc000138a50, 0x0}, 0x0})
	/home/runner/work/tbls/tbls/datasource/datasource.go:116 +0xcc2
github.com/k1LoW/tbls/cmd.glob..func4(0x2a6f040, {0x2bbc1d0, 0x0, 0x0})
	/home/runner/work/tbls/tbls/cmd/diff.go:119 +0x8ec
github.com/spf13/cobra.(*Command).execute(0x2a6f040, {0x2bbc1d0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x2a6fa40)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/k1LoW/tbls/cmd.Execute()
	/home/runner/work/tbls/tbls/cmd/root.go:180 +0x86
main.main()
	/home/runner/work/tbls/tbls/main.go:34 +0x17

goroutine 21 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000168[30](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5821704171?check_suite_focus=true#step:9:30)0)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x92

goroutine 22 [select]:
database/sql.(*DB).connectionOpener(0xc000857380, {0x1e5ab50, 0xc00091fa80})
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:1196 +0x93
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:794 +0x188

goroutine 5 [select]:
net.cgoLookupIP({0x1e5ab50, 0xc0000e4000}, {0x19fbd75, 0x9}, {0xc0000bc270, 0x0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:2[31](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5821704171?check_suite_focus=true#step:9:31) +0x1b7
net.(*Resolver).lookupIP(0x2b777c0, {0x1e5ab50, 0xc0000e[40](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5821704171?check_suite_focus=true#step:9:40)00}, {0x19fbd75, 0x3}, {0xc0000bc270, 0x9})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x1e5ab50, 0xc0000e4000}, 0x0, {0x19fbd75, 0x0}, {0xc0000bc270, 0x0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x2b777d0, 0xc000[46](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5821704171?check_suite_focus=true#step:9:46)20a0, {0xc0000bc280, 0xd}, 0x0)
	/opt/hostedtoolcache/go/1.17.8/x[64](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5821704171?check_suite_focus=true#step:9:64)/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/singleflight/singleflight.go:[88](https://github.com/unstoppabledomains/unstoppable-domains-website/runs/5821704171?check_suite_focus=true#step:9:88) +0x2f1
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 2
Command: /opt/hostedtoolcache/node/***/x64/bin/node
Arguments: /usr/local/lib/node_modules/yarn/lib/cli.js db:docs:diff
Directory: /home/runner/work/unstoppable-domains-website/unstoppable-domains-website/backend
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
Error: Process completed with exit code 2.
##[debug]Finishing: Validate database schema
```

### Environment

- `tbls version` 1.55.0
- Postgres 11.6
- `ubuntu-latest`
- bash

### Config ( .tbls.yml )
```yaml
# DSN (Database Source Name) to connect database
dsn: postgres://postgres:@localhost:5432/unstoppable_website_test?sslmode=disable
# Path to generate document
docPath: dbdocs
format:
  adjust: true
er:
  format: svg
lint:
  requireForeignKeyIndex:
    enabled: true
lintExclude:
    - deprecated_reseller_orders
comments:
  - table: products
    columnComments:
      price: Optional value to override the default price provided by the domain pricing matrix.
  - table: order_products
    columnComments:
      price: The product price at point of sale.
```

**Comment by k1LoW** [comment]
Thank you for your report!

I'm reverting back to the build environment now.

**Comment by k1LoW** [comment]
v1.55.1 is now released. Could you try it?

**Comment by selfagency** [comment]
works, thanks!
